@REM advancedrun /Run "C:\Users\blusc\Desktop\t.cfg"
advancedrun /RUN /RunAs 4 /EXEFilename "D:\Downloads\JarInfectionScanner.exe" /CommandLine "--scan --path ""B:\"""
advancedrun /RUN /RunAs 4 /EXEFilename "D:\Downloads\JarInfectionScanner.exe" /CommandLine "--scan --path ""C:\"""
advancedrun /RUN /RunAs 4 /EXEFilename "D:\Downloads\JarInfectionScanner.exe" /CommandLine "--scan --path ""D:\"""
advancedrun /RUN /RunAs 4 /EXEFilename "D:\Downloads\JarInfectionScanner.exe" /CommandLine "--scan --path ""G:\"""
advancedrun /RUN /RunAs 4 /EXEFilename "D:\Downloads\JarInfectionScanner.exe" /CommandLine "--scan --path ""H:\"""
advancedrun /RUN /RunAs 4 /EXEFilename "D:\Downloads\JarInfectionScanner.exe" /CommandLine "--scan --path ""J:\"""
advancedrun /RUN /RunAs 4 /EXEFilename "D:\Downloads\JarInfectionScanner.exe" /CommandLine "--scan --path ""P:\"""
advancedrun /RUN /RunAs 4 /EXEFilename "D:\Downloads\JarInfectionScanner.exe" /CommandLine "--scan --path ""Z:\"""